# Generated by Django 4.2.10 on 2024-02-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0002_alter_singlenucpol_rs'),
        ('detection_kits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionkit',
            name='markers',
            field=models.ManyToManyField(related_name='detection_kits', to='markers.singlenucpol'),
        ),
    ]
