# Generated by Django 4.2.9 on 2024-02-05 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('detection_kits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionkit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detectionkit',
            name='markers',
            field=models.ManyToManyField(to='markers.singlenucpol'),
        ),
    ]
