# Generated by Django 4.2.9 on 2024-01-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_kits', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionkit',
            name='kit_type',
            field=models.CharField(choices=[('SNP', 'SNP')], default='SNP', max_length=20),
        ),
    ]
