# Generated by Django 4.2.9 on 2024-01-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_kits', '0003_detectionkit_kit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionkit',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
