# Generated by Django 4.2.10 on 2024-03-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_kits', '0004_remove_detectionkit_markers'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='detectionkitmarkers',
            constraint=models.UniqueConstraint(fields=('detection_kit', 'marker'), name='detection_kit_marker_constraint'),
        ),
    ]
