# Generated by Django 4.2.9 on 2024-01-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_kits', '0004_alter_detectionkit_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detectionkit',
            options={'verbose_name': 'SNP detection kit', 'verbose_name_plural': 'SNP detection kits'},
        ),
        migrations.AlterField(
            model_name='detectionkit',
            name='kit_type',
            field=models.CharField(choices=[('SNP', 'in-house SNP assay')], default='SNP', max_length=20),
        ),
    ]
