# Generated by Django 5.0.6 on 2024-06-19 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_kits', '0005_detectionkitmarkers_detection_kit_marker_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detectionkit',
            options={'verbose_name': 'SNP detection kit', 'verbose_name_plural': '2. SNP detection kits'},
        ),
        migrations.AlterModelOptions(
            name='detectionkitmarkers',
            options={'verbose_name': 'Markers in Detection Kit', 'verbose_name_plural': 'Markers in Detection Kit'},
        ),
        migrations.AddField(
            model_name='detectionkitmarkers',
            name='category_order_in_conclusion',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AddField(
            model_name='detectionkitmarkers',
            name='marker_category_in_kit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detectionkitmarkers',
            name='marker_order_in_category',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.CreateModel(
            name='ConclusionsForSNP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genotype', models.CharField(max_length=4)),
                ('conclusion', models.TextField(blank=True, default=None, max_length=2000, null=True)),
                ('det_kit_marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection_kits.detectionkitmarkers')),
            ],
            options={
                'verbose_name': 'conclusion for each SNP genotype',
                'verbose_name_plural': '3. conclusions for each SNP genotype ',
            },
        ),
    ]
