# Generated by Django 5.0.6 on 2024-07-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_kits', '0006_alter_detectionkit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conclusionsforsnp',
            options={'verbose_name': 'conclusion for each SNP genotype', 'verbose_name_plural': '2. conclusions for each SNP genotype '},
        ),
        migrations.AlterModelOptions(
            name='detectionkit',
            options={'verbose_name': 'SNP detection kit', 'verbose_name_plural': '1. SNP detection kits'},
        ),
        migrations.AlterField(
            model_name='detectionkitmarkers',
            name='marker_category_in_kit',
            field=models.CharField(blank=True, choices=[('Механические свойства', 'Механические свойства'), ('Увлажнение', 'Увлажнение'), ('Фотозащита', 'Фотозащита'), ('Воспаление', 'Воспаление'), ('Пищевые непереносимости', 'Пищевые непереносимости'), ('Гормоны', 'Гормоны')], max_length=50, null=True),
        ),
    ]
