# Generated by Django 4.2.9 on 2024-01-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingleNucPol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rs', models.CharField(max_length=20)),
                ('gene_name_short', models.CharField(max_length=20)),
                ('gene_name_full', models.CharField(blank=True, max_length=255, null=True)),
                ('nuc_var_1', models.CharField(choices=[('A', 'A'), ('C', 'C'), ('G', 'G'), ('T', 'T')], max_length=1)),
                ('nuc_var_2', models.CharField(choices=[('A', 'A'), ('C', 'C'), ('G', 'G'), ('T', 'T')], max_length=1)),
                ('nuc_var_1_freq', models.FloatField(blank=True, null=True)),
                ('nuc_var_2_freq', models.FloatField(blank=True, null=True)),
                ('db_snp_link', models.URLField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
    ]
