# Generated by Django 4.2.9 on 2024-01-23 09:34

import django.core.validators
from django.db import migrations, models
import markers.models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0002_alter_singlenucpol_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlenucpol',
            name='db_snp_link',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True, validators=[django.core.validators.URLValidator], verbose_name='dbSNP link'),
        ),
        migrations.AlterField(
            model_name='singlenucpol',
            name='nuc_var_1_freq',
            field=models.FloatField(blank=True, help_text='floating point number. f.e.: 0.5', null=True, validators=[markers.models.validate_freq], verbose_name='allele 1 frequency (from dbSNP)'),
        ),
        migrations.AlterField(
            model_name='singlenucpol',
            name='nuc_var_2_freq',
            field=models.FloatField(blank=True, help_text='floating point number. f.e.: 0.5', null=True, validators=[markers.models.validate_freq], verbose_name='allele 2 frequency (from dbSNP)'),
        ),
        migrations.AlterField(
            model_name='singlenucpol',
            name='rs',
            field=models.CharField(max_length=20, unique=True, validators=[markers.models.validate_rs], verbose_name='Rs id'),
        ),
    ]
