# Generated by Django 4.2.10 on 2024-02-15 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0003_alter_singlenucpol_nuc_var_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlenucpol',
            name='db_snp_link',
            field=models.URLField(blank=True, help_text='==== LINK WILL BE OPENED IN THE SAME TAB! BE CAREFUL ====', max_length=255, null=True, unique=True, validators=[django.core.validators.URLValidator], verbose_name='dbSNP link'),
        ),
    ]
