# Generated by Django 4.2.10 on 2024-03-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0005_alter_singlenucpol_nuc_var_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlenucpol',
            name='nuc_var_1_clin_signif',
            field=models.CharField(blank=True, choices=[('NORM', 'NORM'), ('RISK', 'RISK'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=7, null=True, verbose_name='allele 1 clinical significance'),
        ),
        migrations.AddField(
            model_name='singlenucpol',
            name='nuc_var_2_clin_signif',
            field=models.CharField(blank=True, choices=[('NORM', 'NORM'), ('RISK', 'RISK'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=7, null=True, verbose_name='allele 2 clinical significance'),
        ),
    ]
