# Generated by Django 4.2.9 on 2024-01-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.PositiveIntegerField()),
                ('clinic_id', models.CharField(blank=True, max_length=255, null=True)),
                ('lab_id', models.CharField(max_length=255)),
                ('date_sampled', models.DateField(blank=True, null=True)),
                ('date_delivered', models.DateField()),
                ('dna_concentration', models.PositiveIntegerField()),
                ('dna_quality_260_280', models.FloatField()),
                ('dna_quality_260_230', models.FloatField()),
                ('notes', models.TextField(max_length=255)),
            ],
        ),
    ]
