# Generated by Django 3.2.3 on 2024-01-10 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.PositiveIntegerField()),
                ('clinic_id', models.CharField(blank=True, max_length=255, null=True)),
                ('lab_id', models.CharField(max_length=255)),
                ('date_sampled', models.DateField()),
                ('date_delivered', models.DateField()),
                ('dna_concentration', models.PositiveIntegerField()),
                ('dna_quality_260_280', models.FloatField()),
                ('dna_quality_260_230', models.FloatField()),
                ('notes', models.TextField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
