# Generated by Django 5.0.1 on 2024-02-07 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detection_kits', '0002_initial'),
        ('markers', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsample',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conclusionsnp',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientsample'),
        ),
        migrations.AddField(
            model_name='patientsampledetectionkit',
            name='patient_sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patientsample'),
        ),
        migrations.AddField(
            model_name='patientsampledetectionkit',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='detection_kits.detectionkit'),
        ),
        migrations.AddField(
            model_name='patientsample',
            name='tests',
            field=models.ManyToManyField(through='patients.PatientSampleDetectionKit', to='detection_kits.detectionkit'),
        ),
        migrations.AddField(
            model_name='reportruletwosnp',
            name='snp_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_rules_snp_1', to='markers.singlenucpol'),
        ),
        migrations.AddField(
            model_name='reportruletwosnp',
            name='snp_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_rules_snp_2', to='markers.singlenucpol'),
        ),
        migrations.AddField(
            model_name='reportruletwosnp',
            name='tests',
            field=models.ManyToManyField(related_name='report_rules', to='detection_kits.detectionkit'),
        ),
        migrations.AddField(
            model_name='reportcombinations',
            name='report_rule_two_snp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.reportruletwosnp'),
        ),
        migrations.AddField(
            model_name='resultsnp',
            name='patient_sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientsample'),
        ),
        migrations.AddField(
            model_name='resultsnp',
            name='rs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markers.singlenucpol'),
        ),
        migrations.AddField(
            model_name='resultsnp',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection_kits.detectionkit'),
        ),
        migrations.AddConstraint(
            model_name='conclusionsnp',
            constraint=models.UniqueConstraint(fields=('patient', 'test'), name='patient_and_test_unique_constraint_for_conclusion'),
        ),
        migrations.AddConstraint(
            model_name='patientsampledetectionkit',
            constraint=models.UniqueConstraint(fields=('patient_sample', 'test'), name='patient_and_test_unique_constraint'),
        ),
    ]
