# Generated by Django 4.2.9 on 2024-01-19 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detection_kits', '0003_detectionkit_kit_type'),
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultSNP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rs', models.CharField(max_length=20)),
                ('result', models.CharField(blank=True, max_length=2, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('patient_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientsample')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection_kits.detectionkit')),
            ],
        ),
    ]
