# Generated by Django 4.2.9 on 2024-02-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportruletwosnp',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reportruletwosnp',
            name='snp_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reportruletwosnp',
            name='snp_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
