# Generated by Django 3.2.3 on 2024-01-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patientsample_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsample',
            name='date_sampled',
            field=models.DateField(blank=True, null=True),
        ),
    ]
