# Generated by Django 4.2.9 on 2024-02-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_reportruletwosnp_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportruletwosnp',
            name='note',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='reportruletwosnp',
            name='snp_1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reportruletwosnp',
            name='snp_2',
            field=models.CharField(max_length=20),
        ),
    ]
