# Generated by Django 4.2.10 on 2024-02-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patientsample_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsample',
            name='date_sampled',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
