# Generated by Django 4.2.9 on 2024-01-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_resultsnp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientsample',
            options={'verbose_name': 'Sample', 'verbose_name_plural': 'Samples'},
        ),
        migrations.AlterModelOptions(
            name='patientsampledetectionkit',
            options={'verbose_name': 'Detection kit', 'verbose_name_plural': 'Detection kits'},
        ),
        migrations.AlterModelOptions(
            name='resultsnp',
            options={'verbose_name': 'SNP result', 'verbose_name_plural': 'SNP results'},
        ),
        migrations.AlterField(
            model_name='patientsample',
            name='lab_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
