# Generated by Django 4.2.9 on 2024-01-23 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_kits', '0004_alter_detectionkit_name'),
        ('patients', '0004_alter_patientsample_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRuleTwoSNP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('snp_1', models.CharField(max_length=20)),
                ('snp_2', models.CharField(max_length=20)),
                ('note', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='patientsample',
            name='dna_concentration',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='patientsampledetectionkit',
            constraint=models.UniqueConstraint(fields=('patient_sample', 'test'), name='patient_and_test_unique_constraint'),
        ),
        migrations.AddField(
            model_name='reportruletwosnp',
            name='tests',
            field=models.ManyToManyField(related_name='report_rules', to='detection_kits.detectionkit'),
        ),
    ]
