# Generated by Django 4.2.9 on 2024-02-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_reportruletwosnp_snp_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportruletwosnp',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='reportruletwosnp',
            constraint=models.UniqueConstraint(fields=('tests', 'snp_1', 'snp_2'), name='tests_snp_1_snp_2_constraint'),
        ),
    ]
