# Generated by Django 4.2.9 on 2024-01-23 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_reportruletwosnp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCombinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snp_1_snp_2_combination', models.CharField(max_length=2)),
                ('report', models.TextField(max_length=1000)),
                ('report_rule_two_snp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.reportruletwosnp')),
            ],
        ),
    ]
