# Generated by Django 4.2.10 on 2024-03-07 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_resultsnp_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsample',
            name='date_delivered',
            field=models.DateField(help_text='USE CALENDAR WIDGET'),
        ),
        migrations.AlterField(
            model_name='patientsample',
            name='date_sampled',
            field=models.DateField(help_text='USE CALENDAR WIDGET'),
        ),
        migrations.AlterField(
            model_name='patientsample',
            name='dna_concentration',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='resultsnp',
            name='result',
            field=models.CharField(blank=True, help_text='use only English characters for result.                                USE NUCLEOTIDE ORDER DESIGNATED IN THE RESULT NAME ABOVE', max_length=4, null=True),
        ),
    ]
