# Generated by Django 4.2.9 on 2024-01-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_reportcombinations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportcombinations',
            name='snp_1_snp_2_combination',
        ),
        migrations.AddField(
            model_name='reportcombinations',
            name='snp_1_var_both_strands',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='reportcombinations',
            name='snp_2_var_both_strands',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
