# Generated by Django 4.2.10 on 2024-03-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_patientsample_date_delivered_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conclusionsnp',
            options={'verbose_name': 'conclusion for report', 'verbose_name_plural': '5. Conclusions for reports'},
        ),
        migrations.AlterModelOptions(
            name='patientsample',
            options={'verbose_name': 'Sample', 'verbose_name_plural': '3. Samples'},
        ),
        migrations.AlterModelOptions(
            name='reportcombinations',
            options={'verbose_name': 'report rules: conclusions for genotype combinations', 'verbose_name_plural': '2. report rules: conclusions for genotype combinations'},
        ),
        migrations.AlterModelOptions(
            name='reportruletwosnp',
            options={'verbose_name': 'Report rule for two SNP', 'verbose_name_plural': '1. Report rules for two SNP'},
        ),
        migrations.AlterModelOptions(
            name='resultsnp',
            options={'verbose_name': 'SNP result', 'verbose_name_plural': '4. SNP results'},
        ),
        migrations.AlterField(
            model_name='resultsnp',
            name='result',
            field=models.CharField(blank=True, help_text='use only English characters for result.                            USE NUCLEOTIDE ORDER DESIGNATED ABOVE', max_length=4, null=True),
        ),
    ]
