# Generated by Django 4.2.9 on 2024-01-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_remove_reportcombinations_snp_1_snp_2_combination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcombinations',
            name='report',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
