# Generated by Django 4.2.9 on 2024-01-23 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_reportcombinations_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportcombinations',
            old_name='snp_1_var_both_strands',
            new_name='genotype_snp_1',
        ),
        migrations.RenameField(
            model_name='reportcombinations',
            old_name='snp_2_var_both_strands',
            new_name='genotype_snp_2',
        ),
    ]
