# Generated by Django 4.2.9 on 2024-01-24 11:14

from django.db import migrations, models
import django.db.models.deletion
import patients.models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_kits', '0004_alter_detectionkit_name'),
        ('patients', '0009_rename_snp_1_var_both_strands_reportcombinations_genotype_snp_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportcombinations',
            options={'verbose_name': 'report rules: conclusions for genotype combinations', 'verbose_name_plural': 'report rules: conclusions for genotype combinations'},
        ),
        migrations.AlterField(
            model_name='resultsnp',
            name='rs',
            field=models.CharField(max_length=20, validators=[patients.models.check_if_rs_exists]),
        ),
        migrations.CreateModel(
            name='ConclusionSNP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusion', models.TextField(max_length=5000)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientsample')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection_kits.detectionkit')),
            ],
        ),
    ]
