# Generated by Django 4.2.9 on 2024-01-25 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_alter_conclusionsnp_options_alter_resultsnp_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsample',
            name='dna_quality_260_230',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(3.0)]),
        ),
        migrations.AlterField(
            model_name='patientsample',
            name='dna_quality_260_280',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(3.0)]),
        ),
        migrations.AlterField(
            model_name='patientsample',
            name='notes',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
