# Generated by Django 4.2.10 on 2024-03-12 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detection_kits', '0005_detectionkitmarkers_detection_kit_marker_constraint'),
        ('patients', '0011_alter_patientsample_clinic_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsampledetectionkit',
            name='patient_sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patientsample'),
        ),
        migrations.AlterField(
            model_name='patientsampledetectionkit',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='detection_kits.detectionkit'),
        ),
    ]
